# Generated by Django 4.0 on 2021-12-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_remove_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
