# Generated by Django 4.0 on 2021-12-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0005_remove_file_name_file_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(max_length=50)),
                ('designation', models.TextField(blank=True)),
                ('reference', models.CharField(max_length=200)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('poids_unitaire', models.DecimalField(decimal_places=2, max_digits=6)),
                ('poids_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('composition', models.TextField(blank=True)),
                ('origine', models.IntegerField(blank=True)),
                ('nomenclature_douaniere', models.CharField(max_length=50)),
                ('reference_transport', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(max_length=50)),
                ('designation', models.TextField(blank=True)),
                ('reference', models.CharField(max_length=200)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('poids_unitaire', models.DecimalField(decimal_places=2, max_digits=6)),
                ('poids_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('composition', models.TextField(blank=True)),
                ('origine', models.IntegerField(blank=True)),
                ('nomenclature_douaniere', models.CharField(max_length=50)),
                ('reference_transport', models.CharField(max_length=50)),
            ],
        ),
    ]
