# Generated by Django 4.0 on 2021-12-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0006_deliveryfile_orderfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='profile',
            field=models.CharField(choices=[('Profile 1', 'Client'), ('Profile 2', 'Transporteur')], max_length=20, null=True),
        ),
    ]
