# Generated by Django 4.0 on 2021-12-23 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0008_alter_deliveryfile_poids_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryfile',
            name='uploadedfile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fileupload.file'),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='uploadedfile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fileupload.file'),
        ),
    ]
